const ACTION_TYPE = {
  IMPORT: 'IMPORT',
  ADD: 'ADD',
  ARCHIVE: 'ARCHIVE',
  UPDATE: 'UPDATE',
  UNDO: 'UNDO',
  LOADING: 'LOADING',
  LOAD_MORE: 'LOAD_MORE',
};

const FS = {
  DOCUMENT_PICKER_CANCELED: 'DOCUMENT_PICKER_CANCELED',
};

export {ACTION_TYPE, FS};
